"""refactor session_meta for imported sessions

Revision ID: 002
Revises: 001
Create Date: 2026-07-01 14:06:20.931611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "session_meta",
        sa.Column("source", sa.String(length=16), nullable=False, server_default="imported"),
    )
    op.add_column(
        "session_meta",
        sa.Column("status", sa.String(length=16), nullable=False, server_default="unknown"),
    )
    op.add_column(
        "session_meta",
        sa.Column(
            "imported_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )
    op.add_column("session_meta", sa.Column("last_synced_at", sa.DateTime(), nullable=True))
    op.add_column("session_meta", sa.Column("last_error", sa.String(length=500), nullable=True))
    op.add_column(
        "session_meta",
        sa.Column("has_avatar", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column("session_meta", sa.Column("avatar_path", sa.String(length=256), nullable=True))
    op.add_column("session_meta", sa.Column("avatar_updated_at", sa.DateTime(), nullable=True))

    op.drop_column("session_meta", "first_login_at")
    op.drop_column("session_meta", "last_login_at")
    op.drop_column("session_meta", "login_count")



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_meta', sa.Column('first_login_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('session_meta', sa.Column('last_login_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('session_meta', sa.Column('login_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('session_meta', 'avatar_updated_at')
    op.drop_column('session_meta', 'avatar_path')
    op.drop_column('session_meta', 'has_avatar')
    op.drop_column('session_meta', 'last_error')
    op.drop_column('session_meta', 'last_synced_at')
    op.drop_column('session_meta', 'imported_at')
    op.drop_column('session_meta', 'status')
    op.drop_column('session_meta', 'source')
    # ### end Alembic commands ###